import jsPDF from "jspdf";
import type { ScoredCandidate } from "@/lib/matchingLogic";

function addWrappedText(doc: jsPDF, text: string, x: number, y: number, width: number): number {
  const lines = doc.splitTextToSize(text || "-", width);
  doc.text(lines, x, y);
  return y + lines.length * 6;
}

export function downloadCandidatePdf(candidate: ScoredCandidate) {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  doc.setFillColor(95, 200, 145);
  doc.rect(0, 0, 210, 36, "F");
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(candidate.name, margin, 16);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`${candidate.currentRole} på ${candidate.company}`, margin, 26);

  y = 48;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Matchpoäng: ${candidate.score}/100`, margin, y);
  y += 9;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  candidate.scoreBreakdown.forEach((item) => {
    doc.text(`${item.label}: ${item.weightedScore}p (${item.rawScore}/100 x ${item.weight}%)`, margin, y);
    y += 5;
  });
  doc.text(`Datakvalitet: ${candidate.dataConfidence.level} (${candidate.dataConfidence.score}/100)`, margin, y);
  y += 10;

  doc.setFont("helvetica", "bold");
  doc.text("Beslutsrad", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  y = addWrappedText(doc, candidate.decisionSummary, margin, y, 170) + 8;

  if (candidate.redFlags.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.text("Röda flaggor", margin, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    y = addWrappedText(doc, candidate.redFlags.join(", "), margin, y, 170) + 8;
  }

  doc.setDrawColor(220, 220, 220);
  doc.line(margin, y, 190, y);
  y += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Kontakt", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`E-post: ${candidate.email || "-"}`, margin, y); y += 6;
  doc.text(`Telefon: ${candidate.phone || "-"}`, margin, y); y += 6;
  doc.text(`LinkedIn: ${candidate.linkedin || "-"}`, margin, y); y += 6;
  doc.text(`Plats: ${candidate.location || "-"}`, margin, y); y += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Profil", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Erfarenhet: ${candidate.yearsOfExperience} år`, margin, y); y += 6;
  doc.text(`Källa: ${candidate.source}`, margin, y); y += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Kompetenser", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  y = addWrappedText(doc, candidate.skills.join(", "), margin, y, 170) + 8;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Matchade krav", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  y = addWrappedText(doc, candidate.matchedSkills.join(", ") || "Inga tydliga kompetenskrav matchade.", margin, y, 170) + 8;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Saknade krav", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  y = addWrappedText(doc, candidate.missingSkills.join(", ") || "Inga saknade krav i kompetensdelen.", margin, y, 170) + 8;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Matchanalys", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  addWrappedText(doc, candidate.explanation, margin, y, 170);

  doc.setDrawColor(220, 220, 220);
  doc.line(margin, 280, 190, 280);
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated by NEKTAB Candidate Intelligence - ${new Date().toLocaleDateString()}`, margin, 286);

  doc.save(`${candidate.name.replace(/\s+/g, "_")}_profile.pdf`);
}
